name: Go

on:
  push:
    tags:
      - "*.*.*.*"
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: BbuildFront
        run: cd web/my-app/ &&
          pwd &&
          yarn &&
          yarn build --silent
      - name: BbuildFront2
        run: pwd &&
          cp -a ./web/my-app/build ./web/view &&
          ls -al ./web/view
        # cp -a ./build ..

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64  CGO_ENABLED=1 go build -trimpath -ldflags "-w -s"  .
      # - name: BuildCmd
      #   run: cd cmd && CGO_ENABLED=0 GOOS=linux GOARCH=amd64  CGO_ENABLED=1 go build -trimpath -ldflags "-w -s"  .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./fa4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./fa4

      # - name: Deloly
      #   # scp -i ./deploykey -P 17049 ./cmd/cmd root@cjic.xyz:~/fa4cmd &&
      #   run: chmod 500 ./deploykey &&
      #     ssh  -o StrictHostKeyChecking=no  -i ./deploykey -p 17049 root@cjic.xyz "systemctl stop fa4 " &&
      #     scp -i ./deploykey -P 17049 ./fa4 root@cjic.xyz:~/ &&
      #     ssh -i ./deploykey -p 17049 root@cjic.xyz "systemctl restart fa4"
